#include <stdint.h>

void _reset_handler(void);
static void _default_exception(void);

void _bus_error             (void) __attribute__ ((weak, alias("_default_exception")));
void _address_error         (void) __attribute__ ((weak, alias("_default_exception")));
void _illegal_instruction   (void) __attribute__ ((weak, alias("_default_exception")));
void _division_by_zero      (void) __attribute__ ((weak, alias("_default_exception")));
void _chk_handler           (void) __attribute__ ((weak, alias("_default_exception")));
void _trapv_handler         (void) __attribute__ ((weak, alias("_default_exception")));
void _privilege_violation   (void) __attribute__ ((weak, alias("_default_exception")));
void _trace_handler         (void) __attribute__ ((weak, alias("_default_exception")));

void _uninit_int_handler    (void) __attribute__ ((weak, alias("_default_exception")));
void _spurious_int_handler  (void) __attribute__ ((weak, alias("_default_exception")));
void _level_1_int           (void) __attribute__ ((weak, alias("_default_exception")));
void _level_2_int           (void) __attribute__ ((weak, alias("_default_exception")));
void _level_3_int           (void) __attribute__ ((weak, alias("_default_exception")));
void _level_4_int           (void) __attribute__ ((weak, alias("_default_exception")));
void _level_5_int           (void) __attribute__ ((weak, alias("_default_exception")));
void _level_6_int           (void) __attribute__ ((weak, alias("_default_exception")));
void _level_7_int           (void) __attribute__ ((weak, alias("_default_exception")));

void _trap_0_handler        (void) __attribute__ ((weak, alias("_default_exception")));
void _trap_1_handler        (void) __attribute__ ((weak, alias("_default_exception")));
void _trap_2_handler        (void) __attribute__ ((weak, alias("_default_exception")));
void _trap_3_handler        (void) __attribute__ ((weak, alias("_default_exception")));
void _trap_4_handler        (void) __attribute__ ((weak, alias("_default_exception")));
void _trap_5_handler        (void) __attribute__ ((weak, alias("_default_exception")));
void _trap_6_handler        (void) __attribute__ ((weak, alias("_default_exception")));
void _trap_7_handler        (void) __attribute__ ((weak, alias("_default_exception")));
void _trap_8_handler        (void) __attribute__ ((weak, alias("_default_exception")));
void _trap_9_handler        (void) __attribute__ ((weak, alias("_default_exception")));
void _trap_a_handler        (void) __attribute__ ((weak, alias("_default_exception")));
void _trap_b_handler        (void) __attribute__ ((weak, alias("_default_exception")));
void _trap_c_handler        (void) __attribute__ ((weak, alias("_default_exception")));
void _trap_d_handler        (void) __attribute__ ((weak, alias("_default_exception")));
void _trap_e_handler        (void) __attribute__ ((weak, alias("_default_exception")));
void _trap_f_handler        (void) __attribute__ ((weak, alias("_default_exception")));

extern uint32_t _fstack;

void* vectors[] __attribute__((section(".isr_vector"))) = {
    &_fstack,
    &_reset_handler,
    &_bus_error,
    &_address_error,
    &_illegal_instruction,
    &_division_by_zero,
    &_chk_handler,
    &_trapv_handler,

    &_privilege_violation,
    &_trace_handler,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_uninit_int_handler,

    // Reserved by Motorola
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,

    // Interrupt handlers
    &_spurious_int_handler,
    &_level_1_int,
    &_level_2_int,
    &_level_3_int,
    &_level_4_int,
    &_level_5_int,
    &_level_6_int,
    &_level_7_int,

    // Software TRAP instructions
    &_trap_0_handler,
    &_trap_1_handler,
    &_trap_2_handler,
    &_trap_3_handler,
    &_trap_4_handler,
    &_trap_5_handler,
    &_trap_6_handler,
    &_trap_7_handler,
    &_trap_8_handler,
    &_trap_9_handler,
    &_trap_a_handler,
    &_trap_b_handler,
    &_trap_c_handler,
    &_trap_d_handler,
    &_trap_e_handler,
    &_trap_f_handler,

    // Reserved
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,

    // User Interrupts
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
    &_default_exception,
};

void _default_exception(void) {
    while (1);
}